---
- name: Probe Host
  hosts: localhost
  connection: local
  gather_facts: no
  user: root
  tasks:
  - name: Set Facts
    set_fact:
      # essentially this just looks up the environment variables!
      probe_host: "{{ lookup('env', 'PROBE_HOST') }}"
      probe_port: "{{ lookup('env', 'PROBE_PORT') }}" # these will be passed in through the docker-compose
      probe_delay: "{{ lookup('env', 'PROBE_DELAY') | default(0,true) }}"
      probe_timeout: "{{ lookup('env', 'PROBE_TIMEOUT') | default(180,true) }}"

  - name: Message
    debug:
      msg: >
        Probing {{ probe_host }}:{{ probe_port }} with delay={{ probe_delay }}s
        and timeout={{ probe_timeout }}s
  - name: waiting for response
    local_action: >
      wait_for host={{ probe_host }}
      port={{ probe_port }}
      delay={{ probe_delay }}
      timeout={{ probe_timeout }}

#  - name: Waiting for response
#    local_action: >
#      wait_for host={{ probe_host }} # it is going to keep waiting until this host is reachable
#      port={{ probe_port }}
#      delay={{ probe_delay }}
#      timeout={{ probe_timeout }}